Ok, execute @file:phase3-slot-fit-fallback-and-preclosure-one-shot-prompt.md is now finished with evidence log:
# Copilot Execution Prompt: Phase 3 Slot-Fit + Fallback + Pre-Closure One-Shot

But first we need to re-audit and re-think some existing pages first. Firstly, is the specialization mapping page really that important? I keep thinking about the length of the process, it adds another set up page and may become overwhelming, because instead of that, there is an important process of Master Teachers of each department coordinating with the Grade Level Coordinators (Schedulers) about which teacher will teach what subject for each grade, that is outside of our scope to automate that but does teaching load suffice? There's no controls for this currently, where auto-filling will respect as well. Also, that concern whether a subject teacher can handle teaching a specific subject is resolved and decided between the dept head and the subj teacher, not the scheduler. If so, I think each teacher under a department should be defaulted to be able to teach a subject in any of the subjects under their department, like a teacher from science department can teach, I think we should just map subjects to departments that are fetched from EnrollPro, kind of like how all specializations are in the creating and updating modals of subjects, but instead of specialization, make it per department so that it is less overwhelming since specialization is a lot to handle. 

I just confirmed that stakeholder school actually works by each department head already deciding what grade level and section each faculty teaches for STE programs and higher section programs 1-5, but may sometimes allow schedulers to decide what sections a teacher can teach unless otherwise stated, so auto teaching load button can still exist if the teacher does not want to manually place each one, but placements before generation must be respected and not removed as the department heads have the absolute authority on that. We don't have a user role for department heads so their submission will remain out of scope for the system, the scheduler will have to translate those by manually placing them for now.

Another concern is that in the subjects page right now, I can't delete inactive subjects?? a toast error blocks saying "Cannot delete a subject that is assigned to faculty." but I just searched the subject in teaching load and it's not showing there anwyay? Must be a database level error?

Also, the SPS and SPA specs subjects have the specs info locked, I can't even see it?? Can't view it based on what's enabled in EnrollPro, we must be able to see it and those specs must also be then enabled as subjects since different teachers teach those different specializations, SPA and SPS Specializations label should only be for Class Program and Section Schedule labels, but now we also need to add a Subject Schedule, just like how [CLASS-PROGRAM-SY-2025-2026-GRADE-8.xlsx](stakeholderFiles/CLASS-PROGRAM-SY-2025-2026-GRADE-8.xlsx) has per subject schedules. I've also been made aware that these specialization subjects don't have set rooms, rather they also only try to find available rooms, since they are not really subject lectures, so we don't have to worry about those rooms, we need to be able to handle that fact since our system bottlenecks in room assignments since the system wants a room with each session all the time

Buildings right now are also unrealistic, the stakeholder school does not have a dedicated gym for SPS subjects only like the buildings in the live db suggest.

Teacher X still fills in the faculty page upon timetabling, and when syncing, disappears anyway. I thought we should just make that as UI level, not db level? Like yes it will save as UI and will persist but it will not be part of the faculty table whose data we source from EnrollPro as the source of truth.

In order to get the baseline mapping correct, we really have to piece together what the actual stakeholder data is that concerns our system.

What are the actual buildings, how many rooms being use, what are each sections home room, how many sections can you count in each grade level considering all program types, there are specific rooms like laboratories that are in grade level buildings, does our map editor support that kind of mapping, how many teachers are there, what subjects do they teach, what are the subject-teacher mappings, what are the teaching load for each teacher, etc. All of these based on the files that the stakeholder school has shared with us in stakeholderFiles folder, and we have to make sure that our seeded data and in turn our live db reflects those as much as possible, and then we can validate our generation runs based on that baseline mapping. 

Make sure to go through each file and extract the relevant data points to build that baseline mapping, and then we can also validate that baseline mapping with the stakeholder school to make sure we are aligned on the actual data before we run the generation and see how it performs against that baseline.

This is a lot of work but it is crucial to make sure that our system is actually reflecting the reality of the stakeholder school, and that we are not just working with assumptions or incomplete data. This will also help us identify any gaps in our data or any discrepancies that we need to address before we can confidently run our generation and evaluate its performance.

Make sure to document all of these findings and the baseline mapping in a clear and organized manner in a .md file like we have been doing for the other reports, and then we can share that with the stakeholder school for validation before we proceed with the generation runs. This will also serve as a reference for us to understand the context of the data and the constraints we are working with as we continue to develop and refine our system.

Don't update existing knowledge files yet, as we need to confirm this with the stakeholders.
