// ops/workflow/lib/render.mjs
// Deterministic Markdown register renderer. Output is a pure function of the
// state document content plus its content SHA-256: no timestamps, no file
// paths, no mtimes, no environment values.
import { collectArtifacts } from "./verify.mjs";

const GENERATED_NOTICE = "<!-- atlas-workflow-register: generated; do not edit -->";

const byId = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

function cell(value) {
  return String(value === null || value === undefined ? "" : value)
    .replace(/\|/g, "\\|")
    .replace(/\r?\n/g, " ");
}

function listOrNone(items) {
  return items.length === 0 ? "_none_" : items.map((item) => `\`${cell(item)}\``).join(", ");
}

function iso(value) {
  return value === null ? "_none_" : `\`${value}\``;
}

export function renderRegister(doc, stateSha256) {
  const streams = [...doc.streams].sort((a, b) => byId(a.id, b.id));
  const lines = [];

  lines.push("# ATLAS Delivery Cycle Register (generated)");
  lines.push("");
  lines.push(GENERATED_NOTICE);
  lines.push("");
  lines.push(`Source state content SHA-256: \`${stateSha256}\``);
  lines.push("");
  lines.push("This file is a pure function of the state document content and is regenerated by");
  lines.push("`node ops/workflow/render-register.mjs --state <state> --output <output>`. Do not edit by hand.");
  lines.push("");

  lines.push("## Registry");
  lines.push("");
  lines.push(`- contractVersion: \`${doc.contractVersion}\``);
  lines.push(`- lastUpdatedAt: \`${doc.registry.lastUpdatedAt}\``);
  lines.push(`- lastUpdatedBy: \`${doc.registry.lastUpdatedBy}\``);
  lines.push("");

  lines.push("## Coordination");
  lines.push("");
  lines.push(`- mode: \`${doc.coordination.mode}\``);
  lines.push(`- activeCycleId: ${iso(doc.coordination.activeCycleId)}`);
  lines.push(`- globalNextAction: ${doc.coordination.globalNextAction === null ? "_none_" : cell(doc.coordination.globalNextAction)}`);
  lines.push("");

  lines.push("## Streams");
  lines.push("");
  lines.push("| Stream | Kind | State | Risk | Branch | Next action |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    lines.push(
      `| ${cell(stream.id)} | ${cell(stream.kind)} | ${cell(stream.state)} | ${cell(stream.riskTier)} | ${cell(stream.git.branch ?? "")} | ${cell(stream.nextAction ?? "")} |`,
    );
  }
  lines.push("");

  lines.push("## Awaited and running");
  lines.push("");
  for (const stream of streams) {
    lines.push(`### ${stream.id}`);
    lines.push("");
    lines.push(`- awaited: ${listOrNone(stream.awaited)}`);
    lines.push(`- running: ${listOrNone(stream.running)}`);
    lines.push("");
  }

  lines.push("## Blockers");
  lines.push("");
  lines.push("| Stream | Kind | Detail | Safe work remaining | Safe work items |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    lines.push(
      `| ${cell(stream.id)} | ${cell(stream.blocker.kind)} | ${cell(stream.blocker.detail)} | ${stream.blocker.safeWorkRemaining} | ${cell(listOrNone(stream.blocker.safeWorkItems))} |`,
    );
  }
  lines.push("");

  lines.push("## HIGH approvals");
  lines.push("");
  for (const stream of streams) {
    const approval = stream.approval;
    if (!approval.required && !approval.presentedReady && !approval.granted && stream.approval.boundary === null) continue;
    lines.push(`### ${stream.id}`);
    lines.push("");
    lines.push(`- required: ${approval.required}`);
    lines.push(`- presentedReady: ${approval.presentedReady}`);
    lines.push(`- granted: ${approval.granted}`);
    lines.push(`- operatorIdentity: ${approval.operatorIdentity === null ? "_none_" : `\`${cell(approval.operatorIdentity)}\``}`);
    lines.push(`- approvedAt: ${iso(approval.approvedAt)}`);
    lines.push(`- boundary: ${approval.boundary === null ? "_none_" : cell(approval.boundary)}`);
    lines.push(`- approvedActions: ${listOrNone(approval.approvedActions)}`);
    lines.push(`- requiredObservationIds: ${listOrNone(approval.requiredObservationIds)}`);
    if (approval.execution) {
      lines.push(`- execution.performed: ${approval.execution.performed}`);
      lines.push(`- execution.actionsPerformed: ${listOrNone(approval.execution.actionsPerformed)}`);
      lines.push(`- execution.evidence: ${approval.execution.evidence === null ? "_none_" : cell(approval.execution.evidence)}`);
    }
    lines.push("");
  }

  lines.push("## Observations");
  lines.push("");
  lines.push("| Stream | Id | Target | Status | Checked at | Expires at |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    for (const obs of [...stream.observations].sort((a, b) => byId(a.id, b.id))) {
      lines.push(
        `| ${cell(stream.id)} | ${cell(obs.id)} | ${cell(obs.target)} | ${cell(obs.status)} | ${cell(obs.checkedAt)} | ${cell(obs.expiresAt ?? "")} |`,
      );
    }
  }
  lines.push("");

  lines.push("## Browser custody");
  lines.push("");
  lines.push("### Profiles");
  lines.push("");
  for (const profile of doc.browserCustody.profiles) {
    const activeCount = profile.custody.filter((entry) => entry.status === "ACTIVE").length;
    lines.push(`- \`${cell(profile.profilePath)}\` (active custody entries: ${activeCount})`);
  }
  lines.push("");
  lines.push("| Profile | Owner | Status | Started | Ended |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const profile of doc.browserCustody.profiles) {
    for (const entry of profile.custody) {
      lines.push(`| ${cell(profile.profilePath)} | ${cell(entry.owner)} | ${cell(entry.status)} | ${cell(entry.startedAt ?? "")} | ${cell(entry.endedAt ?? "")} |`);
    }
  }
  lines.push("");
  lines.push("### Logins");
  lines.push("");
  lines.push("| Id | Owner | Profile | Performed | Performed at | Authorized |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const login of doc.browserCustody.logins) {
    lines.push(
      `| ${cell(login.id)} | ${cell(login.owner)} | ${cell(login.profilePath)} | ${login.performed} | ${cell(login.performedAt ?? "")} | ${login.authorization ? "yes" : "no"} |`,
    );
  }
  lines.push("");

  lines.push("## Session routing");
  lines.push("");
  lines.push("| Stream | Role | Decision | Session | Reason |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    for (const role of ["planner", "executor", "qa", "auditor"]) {
      const routing = stream.sessionRouting[role];
      lines.push(
        `| ${cell(stream.id)} | ${role} | ${cell(routing.decision)} | ${routing.sessionId === null ? "_none_" : cell(routing.sessionId)} | ${cell(routing.reason)} |`,
      );
    }
  }
  lines.push("");

  const artifacts = collectArtifacts(doc.streams);
  lines.push("## Pinned artifacts");
  lines.push("");
  lines.push("| Path | SHA-256 |");
  lines.push("| --- | --- |");
  for (const artifact of artifacts) {
    lines.push(`| \`${cell(artifact.path)}\` | \`${cell(artifact.sha256)}\` |`);
  }

  return `${lines.join("\n")}\n`;
}
