// ops/workflow/lib/render.mjs
// Deterministic Markdown register renderer. Output is a pure function of the
// state document content plus its content SHA-256: no timestamps, no file
// paths, no mtimes, no environment values.
import { collectArtifacts } from "./verify.mjs";
import { GATE_CLASSES, deriveReadiness, READINESS_RULE_LINE } from "./readiness.mjs";

const GENERATED_NOTICE = "<!-- atlas-workflow-register: generated; do not edit -->";
export { GENERATED_NOTICE };

const byId = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

function cell(value) {
  return String(value === null || value === undefined ? "" : value)
    .replace(/\|/g, "\\|")
    .replace(/\r?\n/g, " ");
}

function listOrNone(items) {
  return items.length === 0 ? "_none_" : items.map((item) => `\`${cell(item)}\``).join(", ");
}

function iso(value) {
  return value === null ? "_none_" : `\`${value}\``;
}

export function renderRegister(doc, stateSha256) {
  const streams = [...doc.streams].sort((a, b) => byId(a.id, b.id));
  const lines = [];

  lines.push("# ATLAS Delivery Cycle Register (generated)");
  lines.push("");
  lines.push(GENERATED_NOTICE);
  lines.push("");
  lines.push(`Source state content SHA-256: \`${stateSha256}\``);
  lines.push("");
  lines.push("This file is a pure function of the state document content and is regenerated by");
  lines.push("`node ops/workflow/render-register.mjs --state <state> --output <output>`. Do not edit by hand.");
  lines.push("");

  lines.push("## Registry");
  lines.push("");
  lines.push(`- contractVersion: \`${doc.contractVersion}\``);
  lines.push(`- lastUpdatedAt: \`${doc.registry.lastUpdatedAt}\``);
  lines.push(`- lastUpdatedBy: \`${doc.registry.lastUpdatedBy}\``);
  lines.push(`- revision: \`${doc.registry.revision}\``);
  lines.push("");

  lines.push("## Coordination");
  lines.push("");
  lines.push(`- mode: \`${doc.coordination.mode}\``);
  lines.push(`- activeCycleId: ${iso(doc.coordination.activeCycleId)}`);
  lines.push(`- globalNextAction: ${doc.coordination.globalNextAction === null ? "_none_" : cell(doc.coordination.globalNextAction)}`);
  lines.push("");

  lines.push("## Streams");
  lines.push("");
  lines.push("| Stream | Kind | State | Readiness | Risk | Branch | Next action |");
  lines.push("| --- | --- | --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    lines.push(
      `| ${cell(stream.id)} | ${cell(stream.kind)} | ${cell(stream.state)} | ${cell(deriveReadiness(stream.gates).scope)} | ${cell(stream.riskTier)} | ${cell(stream.git.branch ?? "")} | ${cell(stream.nextAction ?? "")} |`,
    );
  }
  lines.push("");

  lines.push("## Gate classes");
  lines.push("");
  lines.push(READINESS_RULE_LINE);
  lines.push("");
  lines.push("| Stream | Class | Planned | Total | Passed | Failed | Blocked | Unperformed |");
  lines.push("| --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    for (const className of GATE_CLASSES) {
      const counters = stream.gates.classes[className];
      lines.push(
        `| ${cell(stream.id)} | ${cell(className)} | ${stream.gates.plan[className]} | ${counters.total} | ${counters.passed} | ${counters.failed} | ${counters.blocked} | ${counters.unperformed} |`,
      );
    }
  }
  lines.push("");

  lines.push("## Git identity");
  lines.push("");
  lines.push("| Stream | Worktree | Branch | Base | Candidate | Integration | Remote observation |");
  lines.push("| --- | --- | --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    const obs = stream.git.remoteObservation;
    const obsCell =
      obs === null
        ? "_none_"
        : `\`${cell(obs.ref)}@${cell(obs.sha)}\` (${cell(obs.kind)}, ${cell(obs.observedAt)})`;
    lines.push(
      `| ${cell(stream.id)} | ${cell(stream.git.worktree ?? "")} | ${cell(stream.git.branch ?? "")} | ${cell(stream.git.baseSha ?? "")} | ${cell(stream.git.candidateSha ?? "")} | ${cell(stream.git.integrationSha ?? "")} | ${obsCell} |`,
    );
  }
  lines.push("");

  lines.push("## Leases");
  lines.push("");
  lines.push("| Id | Stream | Role | State | Worktree | Session | Revision | Updated | Expires |");
  lines.push("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const lease of [...doc.leases].sort((a, b) => byId(a.id, b.id))) {
    lines.push(
      `| ${cell(lease.id)} | ${cell(lease.streamId)} | ${cell(lease.role)} | ${cell(lease.state)} | ${cell(lease.worktree ?? "")} | ${cell(lease.sessionId ?? "")} | ${lease.revision} | ${cell(lease.updatedAt)} | ${cell(lease.expiresAt ?? "")} |`,
    );
  }
  lines.push("");

  lines.push("## Closure receipts");
  lines.push("");
  lines.push("| Stream | Receipt path | SHA-256 |");
  lines.push("| --- | --- | --- |");
  for (const stream of streams) {
    const receipt = stream.closure ? stream.closure.receipt : null;
    lines.push(`| ${cell(stream.id)} | \`${cell(receipt ? receipt.path : "")}\` | \`${cell(receipt ? receipt.sha256 : "")}\` |`);
  }
  lines.push("");

  lines.push("## Resolutions");
  lines.push("");
  lines.push("| Stream | Disposition | Resolver | Superseded by | Resolved at | Resolution |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    const resolution = stream.resolution === undefined ? null : stream.resolution;
    if (resolution === null) continue;
    lines.push(
      `| ${cell(stream.id)} | ${cell(resolution.disposition)} | ${cell(resolution.resolver)} | ${cell(resolution.supersededBy ?? "")} | ${cell(resolution.resolvedAt)} | ${cell(resolution.text)} |`,
    );
  }
  lines.push("");

  lines.push("## Revision windows");
  lines.push("");
  lines.push("| Stream | From revision | To revision | Holder | Declared at |");
  lines.push("| --- | --- | --- | --- | --- |");
  const windows = [...(Array.isArray(doc.registry.windows) ? doc.registry.windows : [])].sort((a, b) => {
    if (a.streamId !== b.streamId) return byId(a.streamId, b.streamId);
    if (a.fromRevision !== b.fromRevision) return a.fromRevision - b.fromRevision;
    // A through-terminal window (`toRevision: null`) has no upper bound and
    // sorts after every bounded span; ordering stays deterministic.
    if (a.toRevision === null) return b.toRevision === null ? 0 : 1;
    if (b.toRevision === null) return -1;
    return a.toRevision - b.toRevision;
  });
  for (const window of windows) {
    const toCell = window.toRevision === null ? "_through-terminal_" : window.toRevision;
    lines.push(
      `| ${cell(window.streamId)} | ${window.fromRevision} | ${toCell} | ${cell(window.holder)} | ${cell(window.declaredAt)} |`,
    );
  }
  lines.push("");

  lines.push("## Awaited and running");
  lines.push("");
  for (const stream of streams) {
    lines.push(`### ${stream.id}`);
    lines.push("");
    lines.push(`- awaited: ${listOrNone(stream.awaited)}`);
    lines.push(`- running: ${listOrNone(stream.running)}`);
    lines.push("");
  }

  lines.push("## Blockers");
  lines.push("");
  lines.push("| Stream | Kind | Detail | Safe work remaining | Safe work items |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    lines.push(
      `| ${cell(stream.id)} | ${cell(stream.blocker.kind)} | ${cell(stream.blocker.detail)} | ${stream.blocker.safeWorkRemaining} | ${cell(listOrNone(stream.blocker.safeWorkItems))} |`,
    );
  }
  lines.push("");

  lines.push("## HIGH approvals");
  lines.push("");
  for (const stream of streams) {
    const approval = stream.approval;
    if (!approval.required && !approval.presentedReady && !approval.granted && stream.approval.boundary === null) continue;
    lines.push(`### ${stream.id}`);
    lines.push("");
    lines.push(`- required: ${approval.required}`);
    lines.push(`- presentedReady: ${approval.presentedReady}`);
    lines.push(`- granted: ${approval.granted}`);
    lines.push(`- operatorIdentity: ${approval.operatorIdentity === null ? "_none_" : `\`${cell(approval.operatorIdentity)}\``}`);
    lines.push(`- approvedAt: ${iso(approval.approvedAt)}`);
    lines.push(`- boundary: ${approval.boundary === null ? "_none_" : cell(approval.boundary)}`);
    lines.push(`- approvedActions: ${listOrNone(approval.approvedActions)}`);
    lines.push(`- requiredObservationIds: ${listOrNone(approval.requiredObservationIds)}`);
    if (approval.execution) {
      lines.push(`- execution.performed: ${approval.execution.performed}`);
      lines.push(`- execution.actionsPerformed: ${listOrNone(approval.execution.actionsPerformed)}`);
      lines.push(`- execution.evidence: ${approval.execution.evidence === null ? "_none_" : cell(approval.execution.evidence)}`);
    }
    lines.push("");
  }

  lines.push("## Observations");
  lines.push("");
  lines.push("| Stream | Id | Target | Status | Checked at | Expires at |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    for (const obs of [...stream.observations].sort((a, b) => byId(a.id, b.id))) {
      lines.push(
        `| ${cell(stream.id)} | ${cell(obs.id)} | ${cell(obs.target)} | ${cell(obs.status)} | ${cell(obs.checkedAt)} | ${cell(obs.expiresAt ?? "")} |`,
      );
    }
  }
  lines.push("");

  lines.push("## Browser custody");
  lines.push("");
  lines.push("### Profiles");
  lines.push("");
  for (const profile of doc.browserCustody.profiles) {
    const activeCount = profile.custody.filter((entry) => entry.status === "ACTIVE").length;
    lines.push(`- \`${cell(profile.profilePath)}\` (active custody entries: ${activeCount})`);
  }
  lines.push("");
  lines.push("| Profile | Owner | Status | Started | Ended |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const profile of doc.browserCustody.profiles) {
    for (const entry of profile.custody) {
      lines.push(`| ${cell(profile.profilePath)} | ${cell(entry.owner)} | ${cell(entry.status)} | ${cell(entry.startedAt ?? "")} | ${cell(entry.endedAt ?? "")} |`);
    }
  }
  lines.push("");
  lines.push("### Logins");
  lines.push("");
  lines.push("| Id | Owner | Profile | Performed | Performed at | Authorized |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const login of doc.browserCustody.logins) {
    lines.push(
      `| ${cell(login.id)} | ${cell(login.owner)} | ${cell(login.profilePath)} | ${login.performed} | ${cell(login.performedAt ?? "")} | ${login.authorization ? "yes" : "no"} |`,
    );
  }
  lines.push("");

  lines.push("## Session routing");
  lines.push("");
  lines.push("| Stream | Role | Decision | Session | Reason |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const stream of streams) {
    for (const role of ["planner", "executor", "qa", "auditor"]) {
      const routing = stream.sessionRouting[role];
      lines.push(
        `| ${cell(stream.id)} | ${role} | ${cell(routing.decision)} | ${routing.sessionId === null ? "_none_" : cell(routing.sessionId)} | ${cell(routing.reason)} |`,
      );
    }
  }
  lines.push("");

  const artifacts = collectArtifacts(doc.streams);
  lines.push("## Pinned artifacts");
  lines.push("");
  lines.push("| Path | SHA-256 |");
  lines.push("| --- | --- |");
  for (const artifact of artifacts) {
    lines.push(`| \`${cell(artifact.path)}\` | \`${cell(artifact.sha256)}\` |`);
  }

  return `${lines.join("\n")}\n`;
}
