-- CreateEnum
CREATE TYPE "room_type" AS ENUM ('CLASSROOM', 'LABORATORY', 'COMPUTER_LAB', 'LIBRARY', 'GYMNASIUM', 'FACULTY_ROOM', 'OFFICE', 'OTHER');

-- AlterTable
ALTER TABLE "rooms" ADD COLUMN     "capacity" INTEGER,
ADD COLUMN     "floor" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "type" "room_type" NOT NULL DEFAULT 'CLASSROOM';
