import type { Dispatch, SetStateAction } from 'react';

import type {
	DraftPlacement,
	DraftBoardState,
	ManualEditProposal,
	ManualEditRecord,
	PreviewResult,
	RoomPreferenceSummaryResponse,
	RoomRequestAppeal,
	ScheduledEntry,
	UnassignedExplanation,
	UnassignedItem,
	Violation,
	ViolationCode,
} from '@/types';

export type LeftRailContentContext = {
	leftTab: 'violations' | 'unassigned' | 'pinned' | 'requests';
	isPreGenerationWorkspace: boolean;
	hardViolationCount: number;
	topBlockers: Violation[];
	violations: Violation[];
	handleViolationSelect: (violation: Violation) => void;
	setSeverityFilter: (value: 'all' | 'hard' | 'soft' | 'conflicts' | 'wellbeing') => void;
	VIOLATION_LABELS: Record<string, string>;
	violationSearch: string;
	setViolationSearch: Dispatch<SetStateAction<string>>;
	filteredViolations: Violation[];
	violationsByCode: Map<ViolationCode, Violation[]>;
	selectedViolation: Violation | null;
	setDrawerViolation: (violation: Violation) => void;
	formatConstraintMessage: (message: string) => string;
	draftBoard: DraftBoardState | null;
	isDesktop: boolean;
	setDragItem: Dispatch<SetStateAction<any>>;
	toast: { info: (message: string) => void; error: (message: string) => void };
	summary: {
		classesProcessed: number;
		assignedCount: number;
		unassignedCount: number;
	} | null;
	filteredUnassignedItems: UnassignedItem[];
	programKindFilteredUnassignedItems: UnassignedItem[];
	UNASSIGNED_REASON_LABELS: Record<string, { label: string; className: string }>;
	unassignedReasonFilter: 'all' | string;
	setUnassignedReasonFilter: Dispatch<SetStateAction<any>>;
	resolveEntryProgramType: (entry: ScheduledEntry | UnassignedItem) => string | null;
	resolveEntryProgramCode: (entry: ScheduledEntry | UnassignedItem) => string | null;
	sectionLabel: (id: number) => string;
	subjectLabel: (id: number) => string;
	kbSelectedSource: any;
	buildUnassignedKey: (item: UnassignedItem) => string;
	followUps: Set<string>;
	expandedUnassigned: Set<string>;
	setExpandedUnassigned: Dispatch<SetStateAction<Set<string>>>;
	unassignedFixSuggestions: Record<string, UnassignedExplanation | null>;
	fixLoading: string | null;
	schoolYearId: number | null;
	runs: Array<{ id: number }>;
	selectedRunId: string;
	defaultSchoolId: number;
	setFixLoading: Dispatch<SetStateAction<string | null>>;
	setUnassignedFixSuggestions: Dispatch<SetStateAction<Record<string, UnassignedExplanation | null>>>;
	entryContextLabel: (entry: ScheduledEntry | UnassignedItem) => string;
	previewEdit: (proposal: ManualEditProposal) => Promise<PreviewResult | null>;
	setDrawerUnassigned: (item: UnassignedItem) => void;
	setFollowUps: Dispatch<SetStateAction<Set<string>>>;
	showSoftConfirm: boolean;
	unassignDropActive: boolean;
	setUnassignDropActive: Dispatch<SetStateAction<boolean>>;
	pinnedRailDropActive: boolean;
	fetchDraftBoardSummary: (syId: number) => Promise<any>;
	preGenPending: any;
	pinsSearch: string;
	setPinsSearch: Dispatch<SetStateAction<string>>;
	pinsGradeFilter: number | 'all';
	setPinsGradeFilter: Dispatch<SetStateAction<number | 'all'>>;
	pinsSectionFilter: number | 'all';
	setPinsSectionFilter: Dispatch<SetStateAction<number | 'all'>>;
	pinsSubjectFilter: number | 'all';
	setPinsSubjectFilter: Dispatch<SetStateAction<number | 'all'>>;
	getDraggedDraftPlacementId: (source: any) => number | null;
	dragItem: any;
	setPendingUnassignId: Dispatch<SetStateAction<number | null>>;
	setShowUnassignConfirm: Dispatch<SetStateAction<boolean>>;
	pinsQueuePage: number;
	setPinsQueuePage: Dispatch<SetStateAction<number>>;
	preGenKbSource: any;
	setPreGenKbSource: Dispatch<SetStateAction<any>>;
	setKbSelectedSource: Dispatch<SetStateAction<any>>;
	rightPanelRef: { current: { expand: () => void } | null };
	selectedEntry: ScheduledEntry | null;
	setSelectedEntry: Dispatch<SetStateAction<ScheduledEntry | null>>;
	setSelectedViolation: Dispatch<SetStateAction<Violation | null>>;
	preGenEntries: ScheduledEntry[];
	gradeForSection: (sectionId: number) => number | null;
	formatTime: (value: string) => string;
	DAY_SHORT: Record<string, string>;
	formatFacultyInitials: (id: number) => string;
	roomLabelShort: (roomId: number) => string;
	GRADE_BADGE: Record<number, string>;
	GRADE_CARD_BG: Record<number, string>;
	roomRequestSummary: RoomPreferenceSummaryResponse | null;
	requestSearch: string;
	setRequestSearch: Dispatch<SetStateAction<string>>;
	requestStatusFilter: 'ALL' | 'SUBMITTED' | 'DRAFT';
	setRequestStatusFilter: Dispatch<SetStateAction<'ALL' | 'SUBMITTED' | 'DRAFT'>>;
	requestDecisionFilter: 'ALL' | 'PENDING' | 'APPROVED' | 'REJECTED';
	setRequestDecisionFilter: Dispatch<SetStateAction<'ALL' | 'PENDING' | 'APPROVED' | 'REJECTED'>>;
	roomRequestError: string | null;
	roomRequestLoading: boolean;
	filteredRoomRequests: any[];
	selectedRequestId: number | null;
	focusRequestInGrid: (requestId: number) => Promise<void>;
	openRequestPreview: (requestId: number) => Promise<void>;
	isPrivilegedUser: boolean;
	focusPinnedPlacement: (placement: DraftPlacement, mode?: 'details' | 'faculty' | 'section' | 'room') => void;
};

export type ScheduleReviewDialogsContext = {
	showUnassignConfirm: boolean;
	setShowUnassignConfirm: Dispatch<SetStateAction<boolean>>;
	setPendingUnassignId: Dispatch<SetStateAction<number | null>>;
	pendingUnassignId: number | null;
	unassignDraftPlacement: (placementId: number) => Promise<void>;
	showGenerateConfirm: boolean;
	setShowGenerateConfirm: Dispatch<SetStateAction<boolean>>;
	draftBoardSummary: DraftBoardState['counts'] | null;
	followUps: Set<string>;
	confirmGenerate: () => void;
	showResetDraftDialog: boolean;
	setShowResetDraftDialog: Dispatch<SetStateAction<boolean>>;
	openPreGenerationWorkspace: (resetExisting: boolean) => Promise<void>;
	showLeavePreGenDialog: boolean;
	setShowLeavePreGenDialog: Dispatch<SetStateAction<boolean>>;
	pendingCenterSwitch: (() => void) | null;
	setPendingCenterSwitch: Dispatch<SetStateAction<(() => void) | null>>;
	requestPreview: any;
	requestPreviewLoading: boolean;
	setRequestPreview: Dispatch<SetStateAction<any>>;
	setSelectedRequestId: Dispatch<SetStateAction<number | null>>;
	setRequestAppeals: Dispatch<SetStateAction<RoomRequestAppeal[]>>;
	setAppealReason: Dispatch<SetStateAction<string>>;
	requestPreviewHardConflicts: Array<{ code: string; humanTitle: string; humanDetail: string; severity: 'HARD' | 'SOFT' }>;
	requestPreviewSoftWarnings: Array<{ code: string; humanTitle: string; humanDetail: string; severity: 'HARD' | 'SOFT' }>;
	requestAppeals: RoomRequestAppeal[];
	appealsLoading: boolean;
	isPrivilegedUser: boolean;
	updateAppealStatus: (appealId: number, status: 'OPEN' | 'UNDER_REVIEW' | 'UPHELD' | 'DENIED') => Promise<void>;
	appealReason: string;
	appealSubmitting: boolean;
	submitAppeal: () => Promise<void>;
	requestReviewerNotes: string;
	setRequestReviewerNotes: Dispatch<SetStateAction<string>>;
	requestReviewSaving: boolean;
	reviewRoomRequest: (decisionStatus: 'APPROVED' | 'REJECTED') => Promise<void>;
	generating: boolean;
	generationElapsed: number;
	showPublishDialog: boolean;
	setShowPublishDialog: Dispatch<SetStateAction<boolean>>;
	softCount: number;
	handlePublishConfirm: () => void;
	showPreGenConfirm: boolean;
	setShowPreGenConfirm: Dispatch<SetStateAction<boolean>>;
	setPreGenConfirmCtx: Dispatch<SetStateAction<any>>;
	setConfirmPreview: Dispatch<SetStateAction<PreviewResult | null>>;
	setConfirmRawPreview: Dispatch<SetStateAction<PreviewResult | null>>;
	setConfirmPreviewError: Dispatch<SetStateAction<string | null>>;
	setConfirmAllowSoftOverride: Dispatch<SetStateAction<boolean>>;
	setConfirmAllowDailyOverride: Dispatch<SetStateAction<boolean>>;
	preGenConfirmCtx: any;
	confirmFacultyId: string;
	setConfirmFacultyId: Dispatch<SetStateAction<string>>;
	confirmPreview: PreviewResult | null;
	confirmRoomId: string;
	setConfirmRoomId: Dispatch<SetStateAction<string>>;
	facultyMap: Map<number, { id: number; firstName: string; lastName: string; department: string | null }>;
	roomMap: Map<number, { id: number; name: string; buildingName: string; buildingShortCode: string | null; isTeachingSpace: boolean }>;
	DAYS: readonly string[];
	DAY_SHORT: Record<string, string>;
	confirmPreviewLoading: boolean;
	confirmPreviewError: string | null;
	confirmDisplacedPlacement: any;
	toast: { error: (message: string) => void };
	openSwapPrompt: (...args: any[]) => void;
	confirmAllowDailyOverride: boolean;
	confirmSaving: boolean;
	commitConfirmPlacement: () => Promise<void>;
	showSwapConfirm: boolean;
	setShowSwapConfirm: Dispatch<SetStateAction<boolean>>;
	setSwapAction: Dispatch<SetStateAction<any>>;
	swapAction: any;
	formatFacultyInitials: (id: number) => string;
	roomLabelShort: (roomId: number) => string;
	subjectLabel: (id: number) => string;
	sectionLabel: (id: number) => string;
	swapSaving: boolean;
	executeSwapAction: () => Promise<void>;
	/** Fix C: swap conflict preview for both legs of a pinned\u21d4pinned swap */
	swapPreview: {
		sourcePreview: PreviewResult | null;
		displacedPreview: PreviewResult | null;
		loading: boolean;
		error: string | null;
	} | null;
	regularSwapPreview: {
		directPreview: PreviewResult | null;
		autoFixBlockingPreview: PreviewResult | null;
		autoFixBlockingTarget: { day: string; startTime: string; endTime: string } | null;
		autoFixSourcePreview: PreviewResult | null;
		autoFixSourceTarget: { day: string; startTime: string; endTime: string } | null;
		recommendedStrategy: 'DIRECT_SWAP' | 'AUTO_FIX_MOVE_BLOCKING' | 'AUTO_FIX_MOVE_SOURCE' | 'BLOCKED' | null;
		loading: boolean;
		error: string | null;
	} | null;
	regularSwapPending: any;
	setRegularSwapPending: Dispatch<SetStateAction<any>>;
	regularSwapSaving: boolean;
	regularSwapStrategy: 'DIRECT_SWAP' | 'AUTO_FIX_MOVE_BLOCKING' | 'AUTO_FIX_MOVE_SOURCE' | null;
	setRegularSwapStrategy: Dispatch<SetStateAction<'DIRECT_SWAP' | 'AUTO_FIX_MOVE_BLOCKING' | 'AUTO_FIX_MOVE_SOURCE' | null>>;
	executeRegularSwap: () => Promise<void>;
	showSoftConfirm: boolean;
	setShowSoftConfirm: Dispatch<SetStateAction<boolean>>;
	softConfirmWarnings: Violation[];
	commitLoading: boolean;
	formatConstraintMessage: (message: string) => string;
	setPendingCommitProposal: Dispatch<SetStateAction<ManualEditProposal | null>>;
	setPreviewResult: Dispatch<SetStateAction<PreviewResult | null>>;
	setSoftConfirmWarnings: Dispatch<SetStateAction<Violation[]>>;
	setDragItem: Dispatch<SetStateAction<any>>;
	pendingCommitProposal: ManualEditProposal | null;
	commitEdit: (proposal: ManualEditProposal, allowSoftOverride?: boolean) => Promise<void>;
	showAssignmentPicker: boolean;
	setShowAssignmentPicker: Dispatch<SetStateAction<boolean>>;
	setAssignPickerTarget: Dispatch<SetStateAction<any>>;
	assignPickerTarget: any;
	assignPickerFacultyId: string;
	setAssignPickerFacultyId: Dispatch<SetStateAction<string>>;
	assignPickerRoomId: string;
	setAssignPickerRoomId: Dispatch<SetStateAction<string>>;
	confirmAssignmentPicker: () => Promise<void>;
	showEditHistory: boolean;
	setShowEditHistory: Dispatch<SetStateAction<boolean>>;
	editHistory: ManualEditRecord[];
};